spring:
  application:
    name: fitchingweb

  profiles:
    include: oauth, jwt
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #
  #    hikari:
  #      driver-class-name: org.h2.Driver
  #      jdbc-url: jdbc:h2:~/test
  #      username: sa
  #      password:

  datasource:
    url: jdbc:mariadb://localhost:3306/fitchingdb
    username: fitchingmaster
    password: 12341234!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: always
