spring:

  # Mariadb Database 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/fitchingdb
    username: fitchingmaster
    password: 12341234!
    driver-class-name: org.mariadb.jdbc.Driver


  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

        # hibernate가 자동으로 스키마를 생성하는 옵션(기본 옵션 : auto : create)
        # none으로 설정하지 않을 경우, 스프링 서버 시작마다 db table을 새롭게 생성함
        # 따라서 운영 환경에서는 무조건 none으로 설정하여야 db가 초기화되지 않음
#        hbm2ddl:
#          auto: none
