spring:
  application:
    name: fitchingweb

  # 활성 프로필 설정
  profiles:
    active: dev
    group:
      "local" : "local, oauth, jwt"
      "dev" : "dev, oauth, jwt"

server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-password: 12341234
