spring:
  application:
    name: fitchingWeb

  profiles:
    include: oauth, jwt
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always



